name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build-same-tgz
      - name: Upload binary tarball to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build.outputs.BINARY_TARBALL }}"
          asset_name: "Tarball"
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload binary tarball signature to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build.outputs.BINARY_TARBALL_SIGNATURE }}"
          tag: ${{ github.ref }}
          overwrite: true
