name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$PRIVATE_PEM" > private.pem'
        shell: bash
        env:
          PRIVATE_PEM: ${{secrets.PRIVATE_PEM}}
      - name: build
        run: make build-same-tgz
        env:
          PRIVATE_KEY_PASSPHRASE: ${{secrets.PRIVATE_KEY_PASSPHRASE}}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Upload binary tarball to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BINARY_TARBALL }}
          asset_name: ${{ env.BINARY_TARBALL_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload binary tarball signature to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BINARY_TARBALL_SIGNATURE }}
          asset_name: ${{ env.BINARY_TARBALL_SIGNATURE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
